// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlrvMgdXiTbdkGsFT58NJtmP989_atyAE',
    appId: '1:350903303620:web:b3b03482d3a9f2cab87891',
    messagingSenderId: '350903303620',
    projectId: 'chitchat-c9720',
    authDomain: 'chitchat-c9720.firebaseapp.com',
    storageBucket: 'chitchat-c9720.appspot.com',
    measurementId: 'G-GQ60NKWBVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR1srDkbv8Dr9Rs11RmvdlR3uwrhFvYYA',
    appId: '1:350903303620:android:06c5f7707085a268b87891',
    messagingSenderId: '350903303620',
    projectId: 'chitchat-c9720',
    storageBucket: 'chitchat-c9720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_rQ62RneeRSbM4a2BsFQ5gxcjFWWKCd0',
    appId: '1:350903303620:ios:cb8412a8453640bbb87891',
    messagingSenderId: '350903303620',
    projectId: 'chitchat-c9720',
    storageBucket: 'chitchat-c9720.appspot.com',
    iosClientId: '350903303620-v5mcakco3hbe941q906sp7ac3iv44h0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );
}
